In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
import os

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ranamuhammmadusman/wheat-economics-comprehensive-farm-data")

print("Path to dataset files:", path)

In [2]:
ls .\dataset

 Volume in drive C is OS
 Volume Serial Number is 6CFA-EFAE

 Directory of C:\Users\JOHN\Documents\Data Science Practice\re_exam_datascience_ML_DL\dataset

01/18/2026  03:22 PM    <DIR>          .
01/18/2026  03:22 PM    <DIR>          ..
01/18/2026  03:02 PM         1,109,561 final_wheat_data.csv
12/04/2025  11:32 PM           202,452 marketing_campaign_data_messy.csv
               2 File(s)      1,312,013 bytes
               2 Dir(s)  115,407,167,488 bytes free

In [2]:
dataset = pd.read_csv("./dataset/final_wheat_data.csv")
dataset

,commodity,category,item,item2,units,size,region,country,year,value,survey_base_year,note
0,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,1998,110.95,Base survey of 1998,NaN
1,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,1999,95.73,Base survey of 1998,NaN
2,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2000,92.50,Base survey of 1998,NaN
3,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2001,95.22,Base survey of 1998,NaN
4,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2002,91.51,Base survey of 1998,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5998,Wheat,Production practices,Irrigated,Irrigated (percent of acres),percent of acres,No specific size,Mississippi Portal,United States,1999,0.00,Base survey of 1998,NaN
5999,Wheat,Production practices,Irrigated,Irrigated (percent of acres),percent of acres,No specific size,Mississippi Portal,United States,2000,0.00,Base survey of 1998,NaN
6000,Wheat,Production practices,Irrigated,Irrigated (percent of acres),percent of acres,No specific size,Mississippi Portal,United States,2001,0.00,Base survey of 1998,NaN
6001,Wheat,Production practices,Irrigated,Irrigated (percent of acres),percent of acres,No specific size,Mississippi Portal,United States,2002,0.00,Base survey of 1998,NaN
6002,Wheat,Production practices,Irrigated,Irrigated (percent of acres),percent of acres,No specific size,Mississippi Portal,United States,2003,0.00,Base survey of 1998,NaN

In [3]:
df_1 = dataset.drop_duplicates()
df_1["column"] = df_1["item"].str.replace(' ', '_').str.replace(',', '_').str.replace('/', '_').str.replace('¹', '1').str.replace('²', '2').str.replace('³', '3')
df_1["column"] = df_1["column"].str.replace('__', '_').str.lower()
df_1.shape

(6003, 13)

In [4]:
df_1.item.unique()

array(['Primary product, grain',
       'Secondary product, silage/straw/grazing',
       'Total, gross value of production', 'Seed', 'Fertilizer ¹',
       'Chemicals', 'Custom services', 'Fuel, lube, and electricity',
       'Repairs', 'Other variable expenses ²',
       'Interest on operating inputs', 'Total, operating costs',
       'Hired labor', 'Opportunity cost of unpaid labor',
       'Capital recovery of machinery and equipment',
       'Opportunity cost of land', 'Taxes and insurance',
       'General farm overhead', 'Total, allocated overhead',
       'Total, costs listed',
       'Value of production less total costs listed',
       'Value of production less operating costs', 'Yield', 'Price',
       'Enterprise size', 'Winter wheat', 'Winter wheat ³',
       'Spring wheat', 'Spring wheat ³', 'Durum wheat', 'Durum wheat ³',
       'Dryland', 'Dryland ³', 'Irrigated', 'Irrigated ³'], dtype=object)

In [4]:
df_1.column.unique()

array(['primary_product_grain', 'secondary_product_silage_straw_grazing',
       'total_gross_value_of_production', 'seed', 'fertilizer_1',
       'chemicals', 'custom_services', 'fuel_lube_and_electricity',
       'repairs', 'other_variable_expenses_2',
       'interest_on_operating_inputs', 'total_operating_costs',
       'hired_labor', 'opportunity_cost_of_unpaid_labor',
       'capital_recovery_of_machinery_and_equipment',
       'opportunity_cost_of_land', 'taxes_and_insurance',
       'general_farm_overhead', 'total_allocated_overhead',
       'total_costs_listed',
       'value_of_production_less_total_costs_listed',
       'value_of_production_less_operating_costs', 'yield', 'price',
       'enterprise_size', 'winter_wheat', 'winter_wheat_3',
       'spring_wheat', 'spring_wheat_3', 'durum_wheat', 'durum_wheat_3',
       'dryland', 'dryland_3', 'irrigated', 'irrigated_3'], dtype=object)

In [6]:
df_1.item2.unique()

array(['Primary product, grain',
       'Secondary product, silage/straw/grazing',
       'Total, gross value of production', 'Seed', 'Fertilizer ¹',
       'Chemicals', 'Custom services', 'Fuel, lube, and electricity',
       'Repairs', 'Other variable expenses ²',
       'Interest on operating inputs', 'Total, operating costs',
       'Hired labor', 'Opportunity cost of unpaid labor',
       'Capital recovery of machinery and equipment',
       'Opportunity cost of land', 'Taxes and insurance',
       'General farm overhead', 'Total, allocated overhead',
       'Total, costs listed',
       'Value of production less total costs listed',
       'Value of production less operating costs',
       'Yield (bushels per planted acre)',
       'Price (dollars per bushel at harvest)',
       'Enterprise size (planted acres)',
       'Winter wheat (percent of acres)',
       'Winter wheat ³  (percent of acres)',
       'Spring wheat (percent of acres)',
       'Spring wheat ³  (percent of acres)',
       'Durum wheat (percent of acres)',
       'Durum wheat ³  (percent of acres)', 'Dryland (percent of acres)',
       'Dryland ³  (percent of acres)', 'Irrigated (percent of acres)',
       'Irrigated ³  (percent of acres)'], dtype=object)

In [7]:
df_1.region.unique()

array(['U.S. total', 'Heartland', 'Northern Crescent',
       'Northern Great Plains', 'Prairie Gateway', 'Southern Seaboard',
       'Basin and Range', 'Fruitful Rim', 'Mississippi Portal'],
      dtype=object)

In [15]:
df_1.year.unique()

array([1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
       2020, 2021, 2022, 2023, 2024])

In [10]:
df_1.commodity.unique()

array(['Wheat'], dtype=object)

In [9]:
df_1.country.unique()

array(['United States'], dtype=object)

In [17]:
df_1.year.nunique()

27

In [18]:
df_1.loc[df_1['region']=="U.S. total"].item2.unique()

array(['Primary product, grain',
       'Secondary product, silage/straw/grazing',
       'Total, gross value of production', 'Seed', 'Fertilizer ¹',
       'Chemicals', 'Custom services', 'Fuel, lube, and electricity',
       'Repairs', 'Other variable expenses ²',
       'Interest on operating inputs', 'Total, operating costs',
       'Hired labor', 'Opportunity cost of unpaid labor',
       'Capital recovery of machinery and equipment',
       'Opportunity cost of land', 'Taxes and insurance',
       'General farm overhead', 'Total, allocated overhead',
       'Total, costs listed',
       'Value of production less total costs listed',
       'Value of production less operating costs',
       'Yield (bushels per planted acre)',
       'Price (dollars per bushel at harvest)',
       'Enterprise size (planted acres)',
       'Winter wheat (percent of acres)',
       'Spring wheat (percent of acres)',
       'Durum wheat (percent of acres)', 'Dryland (percent of acres)',
       'Irrigated (percent of acres)'], dtype=object)

In [11]:
df_1.loc[df_1['region']=="U.S. total",["item2","year", "value"]].groupby(by=["year"]).sum()

                                                  item2    value
year
1998  Primary product, grainSecondary product, silag...  1269.73
1999  Primary product, grainSecondary product, silag...  1210.08
2000  Primary product, grainSecondary product, silag...  1208.60
2001  Primary product, grainSecondary product, silag...  1229.10
2002  Primary product, grainSecondary product, silag...  1202.15
2003  Primary product, grainSecondary product, silag...  1374.75
2004  Primary product, grainSecondary product, silag...  1535.74
2005  Primary product, grainSecondary product, silag...  1521.34
2006  Primary product, grainSecondary product, silag...  1573.71
2007  Primary product, grainSecondary product, silag...  1841.64
2008  Primary product, grainSecondary product, silag...  2425.30
2009  Primary product, grainSecondary product, silag...  2016.90
2010  Primary product, grainSecondary product, silag...  1993.72
2011  Primary product, grainSecondary product, silag...  2283.44
2012  Primary product, grainSecondary product, silag...  2541.66
2013  Primary product, grainSecondary product, silag...  2330.52
2014  Primary product, grainSecondary product, silag...  2181.79
2015  Primary product, grainSecondary product, silag...  2047.37
2016  Primary product, grainSecondary product, silag...  2023.85
2017  Primary product, grainSecondary product, silag...  2201.87
2018  Primary product, grainSecondary product, silag...  2365.57
2019  Primary product, grainSecondary product, silag...  2351.08
2020  Primary product, grainSecondary product, silag...  2304.42
2021  Primary product, grainSecondary product, silag...  2536.77
2022  Primary product, grainSecondary product, silag...  2785.58
2023  Primary product, grainSecondary product, silag...  2605.93
2024  Primary product, grainSecondary product, silag...  2484.70

In [25]:
df_1.loc[df_1['region']=="U.S. total",["item2"]]

                             item2
0           Primary product, grain
1           Primary product, grain
2           Primary product, grain
3           Primary product, grain
4           Primary product, grain
...                            ...
5833  Irrigated (percent of acres)
5834  Irrigated (percent of acres)
5835  Irrigated (percent of acres)
5836  Irrigated (percent of acres)
5837  Irrigated (percent of acres)

[810 rows x 1 columns]

In [12]:
df_1.loc[(df_1['region'] == "U.S. total") & (df_1['item'] != df_1['item2']),["item", "item2","year", "value"]].item.unique()

array(['Yield', 'Price', 'Enterprise size', 'Winter wheat',
       'Spring wheat', 'Durum wheat', 'Dryland', 'Irrigated'],
      dtype=object)

In [13]:
df_1.loc[(df_1['region'] == "U.S. total") & (df_1['item'] != df_1['item2']),["item", "item2","year", "value"]].item2.unique()

array(['Yield (bushels per planted acre)',
       'Price (dollars per bushel at harvest)',
       'Enterprise size (planted acres)',
       'Winter wheat (percent of acres)',
       'Spring wheat (percent of acres)',
       'Durum wheat (percent of acres)', 'Dryland (percent of acres)',
       'Irrigated (percent of acres)'], dtype=object)

In [14]:
df_1.loc[(df_1['region'] == "U.S. total") & (df_1['item'].isin(["Price", "Hired labor", "Chemicals",'Opportunity cost of land', 'Total, costs listed', 'Primary product, grain'])) & (df_1['year'] == df_1['year'].min())]

,commodity,category,item,item2,units,size,region,country,year,value,survey_base_year,note,column
0,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,1998,110.95,Base survey of 1998,NaN,Primary_product_grain
1005,Wheat,Operating costs,Chemicals,Chemicals,dollars per planted acre,No specific size,U.S. total,United States,1998,7.36,Base survey of 1998,NaN,Chemicals
2412,Wheat,Allocated overhead,Hired labor,Hired labor,dollars per planted acre,No specific size,U.S. total,United States,1998,2.12,Base survey of 1998,NaN,Hired_labor
3015,Wheat,Allocated overhead,Opportunity cost of land,Opportunity cost of land,dollars per planted acre,No specific size,U.S. total,United States,1998,37.52,Base survey of 1998,NaN,Opportunity_cost_of_land
3819,Wheat,Costs listed,"Total, costs listed","Total, costs listed",dollars per planted acre,No specific size,U.S. total,United States,1998,165.19,Base survey of 1998,NaN,Total_costs_listed
4623,Wheat,Supporting information,Price,Price (dollars per bushel at harvest),dollars per bushel at harvest,No specific size,U.S. total,United States,1998,2.68,Base survey of 1998,NaN,Price

In [65]:
df_1.loc[(df_1['region'] == "U.S. total") & (df_1['item'].isin(['Opportunity cost of land', 'Total, costs listed', 'Primary product, grain']))].sort_values(by='year')

,commodity,category,item,item2,units,size,region,country,year,value,survey_base_year,note
0,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,1998,110.95,Base survey of 1998,NaN
3015,Wheat,Allocated overhead,Opportunity cost of land,Opportunity cost of land,dollars per planted acre,No specific size,U.S. total,United States,1998,37.52,Base survey of 1998,NaN
3819,Wheat,Costs listed,"Total, costs listed","Total, costs listed",dollars per planted acre,No specific size,U.S. total,United States,1998,165.19,Base survey of 1998,NaN
3016,Wheat,Allocated overhead,Opportunity cost of land,Opportunity cost of land,dollars per planted acre,No specific size,U.S. total,United States,1999,37.89,Base survey of 1998,NaN
3820,Wheat,Costs listed,"Total, costs listed","Total, costs listed",dollars per planted acre,No specific size,U.S. total,United States,1999,166.15,Base survey of 1998,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2023,311.54,Base survey of 2022,NaN
3844,Wheat,Costs listed,"Total, costs listed","Total, costs listed",dollars per planted acre,No specific size,U.S. total,United States,2023,396.92,Base survey of 2022,NaN
3041,Wheat,Allocated overhead,Opportunity cost of land,Opportunity cost of land,dollars per planted acre,No specific size,U.S. total,United States,2024,66.07,Base survey of 2022,NaN
26,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2024,279.78,Base survey of 2022,NaN
3845,Wheat,Costs listed,"Total, costs listed","Total, costs listed",dollars per planted acre,No specific size,U.S. total,United States,2024,390.98,Base survey of 2022,NaN

In [67]:
df_1["item"][5]

'Primary product, grain'

In [121]:
cop = pd.DataFrame(columns=['Opportunity cost of land','Total, costs listed', 'Total, gross value of production', 'Yield', 'Price', 'year'])
cop.columns

Index(['Opportunity cost of land', 'Total, costs listed',
       'Total, gross value of production', 'Yield', 'Price', 'year'],
      dtype='object')

In [122]:
num = 0
for i in df_1['year'].unique():
    cop.loc[num, 'year'] = i
    for j in cop.columns:
        if j != 'year': 
            cop.loc[num, j] = df_1.loc[(df_1['item']==j)&(df_1['year']==i)&(df_1['region']=='U.S. total'), 'value'].iloc[0]
    num +=1

In [123]:
cop

,Opportunity cost of land,"Total, costs listed","Total, gross value of production",Yield,Price,year
0,37.52,165.19,114.27,41.0,2.68,1998
1,37.89,166.15,98.78,39.0,2.48,1999
2,38.53,173.86,95.7,38.0,2.46,2000
3,39.54,183.34,98.4,35.0,2.76,2001
4,39.19,175.63,95.17,28.0,3.28,2002
5,39.93,191.12,130.02,41.0,3.11,2003
6,37.8,190.6,142.48,40.0,3.44,2004
7,41.07,207.45,132.68,40.0,3.17,2005
8,40.86,216.78,144.01,33.0,4.12,2006
9,43.54,231.99,204.11,37.0,5.25,2007
10,48.9,277.4,333.83,41.0,7.86,2008
11,46.2,263.24,228.7,40.0,5.54,2009
12,46.83,257.4,222.24,45.0,4.75,2010
13,52.65,287.57,285.71,38.0,7.35,2011
14,57.58,302.0,342.7,44.0,7.58,2012
15,63.7,312.03,286.63,39.0,7.09,2013
16,65.06,316.28,247.53,37.0,6.44,2014
17,65.99,310.5,213.9,40.0,5.12,2015
18,62.89,300.94,208.46,51.0,3.93,2016
19,57.55,306.76,224.61,46.0,4.8,2017
20,59.47,322.5,258.28,49.0,5.21,2018
21,59.73,326.57,252.63,53.0,4.64,2019
22,60.04,319.74,242.31,52.0,4.61,2020
23,62.13,353.76,288.65,42.0,6.67,2021
24,62.1,401.81,367.0,40.0,8.95,2022
25,64.04,396.92,320.56,41.0,7.52,2023
26,66.07,390.98,287.33,51.0,5.53,2024

In [103]:
cop.loc[0, 'Opportunity cost of land']

np.float64(37.52)

In [96]:
df_1.loc[(df_1['item']=='Opportunity cost of land')&(df_1['year']==2002)&(df_1['region']=='U.S. total'), 'value'].iloc[0]

np.float64(39.19)

In [124]:
df_1.units.nunique()

5

In [125]:
df_1.units.unique()

array(['dollars per planted acre', 'bushels per planted acre',
       'dollars per bushel at harvest', 'planted acres',
       'percent of acres'], dtype=object)

In [31]:
df_a = df_1.loc[df_1['units']=='dollars per planted acre']
df_a

,commodity,category,item,item2,units,size,region,country,year,value,survey_base_year,note,column
0,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,1998,110.95,Base survey of 1998,NaN,primary_product_grain
1,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,1999,95.73,Base survey of 1998,NaN,primary_product_grain
2,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2000,92.50,Base survey of 1998,NaN,primary_product_grain
3,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2001,95.22,Base survey of 1998,NaN,primary_product_grain
4,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2002,91.51,Base survey of 1998,NaN,primary_product_grain
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4417,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,1999,60.03,Base survey of 1998,NaN,value_of_production_less_operating_costs
4418,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,2000,73.56,Base survey of 1998,NaN,value_of_production_less_operating_costs
4419,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,2001,58.00,Base survey of 1998,NaN,value_of_production_less_operating_costs
4420,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,2002,51.06,Base survey of 1998,NaN,value_of_production_less_operating_costs
4421,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,2003,55.41,Base survey of 1998,NaN,value_of_production_less_operating_costs

In [22]:
col_a = list(df_a.column.unique())
col_a.append('region')
cop_1 = pd.DataFrame(columns=col_a)
cop_1.columns

Index(['primary_product_grain', 'secondary_product_silage_straw_grazing',
       'total_gross_value_of_production', 'seed', 'fertilizer_1', 'chemicals',
       'custom_services', 'fuel_lube_and_electricity', 'repairs',
       'other_variable_expenses_2', 'interest_on_operating_inputs',
       'total_operating_costs', 'hired_labor',
       'opportunity_cost_of_unpaid_labor',
       'capital_recovery_of_machinery_and_equipment',
       'opportunity_cost_of_land', 'taxes_and_insurance',
       'general_farm_overhead', 'total_allocated_overhead',
       'total_costs_listed', 'value_of_production_less_total_costs_listed',
       'value_of_production_less_operating_costs', 'region'],
      dtype='object')

In [38]:
df_a['region'].unique()

array(['U.S. total', 'Heartland', 'Northern Crescent',
       'Northern Great Plains', 'Prairie Gateway', 'Southern Seaboard',
       'Basin and Range', 'Fruitful Rim', 'Mississippi Portal'],
      dtype=object)

In [46]:
df_a.loc[(df_a['column']=='primary_product_grain') & (df_a['year']==2000) & (df_a['region']=='Southern Seaboard')]
#& (df_a['region']=='Southern Seaboard')

,commodity,category,item,item2,units,size,region,country,year,value,survey_base_year,note,column
137,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,Southern Seaboard,United States,2000,97.13,Base survey of 1998,NaN,primary_product_grain

In [32]:
num = 0
for i in df_a['year'].unique():
    for x in df_a['region'].unique():
        cop_1.loc[num, 'year'] = i
        cop_1.loc[num, 'region'] = x
        
        for j in cop_1.columns:
            if j != 'year' and j != 'region':
                # Filter the dataframe
                filtered_df = df_a.loc[(df_a['column']==j) & (df_a['year']==i) & (df_a['region']==x), 'value']
                
                # Check if there's any matching data
                if not filtered_df.empty:
                    cop_1.loc[num, j] = filtered_df.iloc[0]
                else:
                    # Handle missing data - you can set to NaN, 0, or leave as is
                    cop_1.loc[num, j] = None  # or np.nan, or 0
                    print(f"Warning: No data found for column={j}, year={i}, region={x}")
        
        num += 1

Warning: No data found for column=primary_product_grain, year=2004, region=Southern Seaboard
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2004, region=Southern Seaboard
Warning: No data found for column=total_gross_value_of_production, year=2004, region=Southern Seaboard
Warning: No data found for column=seed, year=2004, region=Southern Seaboard
Warning: No data found for column=fertilizer_1, year=2004, region=Southern Seaboard
Warning: No data found for column=chemicals, year=2004, region=Southern Seaboard
Warning: No data found for column=custom_services, year=2004, region=Southern Seaboard
Warning: No data found for column=fuel_lube_and_electricity, year=2004, region=Southern Seaboard
Warning: No data found for column=repairs, year=2004, region=Southern Seaboard
Warning: No data found for column=other_variable_expenses_2, year=2004, region=Southern Seaboard
Warning: No data found for column=interest_on_operating_inputs, year=2004, region=Southern Seaboard
Warning: No data found for column=total_operating_costs, year=2004, region=Southern Seaboard
Warning: No data found for column=hired_labor, year=2004, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_unpaid_labor, year=2004, region=Southern Seaboard
Warning: No data found for column=capital_recovery_of_machinery_and_equipment, year=2004, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_land, year=2004, region=Southern Seaboard
Warning: No data found for column=taxes_and_insurance, year=2004, region=Southern Seaboard
Warning: No data found for column=general_farm_overhead, year=2004, region=Southern Seaboard
Warning: No data found for column=total_allocated_overhead, year=2004, region=Southern Seaboard
Warning: No data found for column=total_costs_listed, year=2004, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_total_costs_listed, year=2004, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_operating_costs, year=2004, region=Southern Seaboard
Warning: No data found for column=primary_product_grain, year=2004, region=Mississippi Portal
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2004, region=Mississippi Portal
Warning: No data found for column=total_gross_value_of_production, year=2004, region=Mississippi Portal
Warning: No data found for column=seed, year=2004, region=Mississippi Portal
Warning: No data found for column=fertilizer_1, year=2004, region=Mississippi Portal
Warning: No data found for column=chemicals, year=2004, region=Mississippi Portal
Warning: No data found for column=custom_services, year=2004, region=Mississippi Portal
Warning: No data found for column=fuel_lube_and_electricity, year=2004, region=Mississippi Portal
Warning: No data found for column=repairs, year=2004, region=Mississippi Portal
Warning: No data found for column=other_variable_expenses_2, year=2004, region=Mississippi Portal
Warning: No data found for column=interest_on_operating_inputs, year=2004, region=Mississippi Portal
Warning: No data found for column=total_operating_costs, year=2004, region=Mississippi Portal
Warning: No data found for column=hired_labor, year=2004, region=Mississippi Portal
Warning: No data found for column=opportunity_cost_of_unpaid_labor, year=2004, region=Mississippi Portal
Warning: No data found for column=capital_recovery_of_machinery_and_equipment, year=2004, region=Mississippi Portal
Warning: No data found for column=opportunity_cost_of_land, year=2004, region=Mississippi Portal
Warning: No data found for column=taxes_and_insurance, year=2004, region=Mississippi Portal
Warning: No data found for column=general_farm_overhead, year=2004, region=Mississippi Portal
Warning: No data found for column=total_allocated_overhead, year=2004, region=Mississippi Portal
Warning: No data found for column=total_costs_listed, year=2004, region=Mississippi Portal
Warning: No data found for column=value_of_production_less_total_costs_listed, year=2004, region=Mississippi Portal
Warning: No data found for column=value_of_production_less_operating_costs, year=2004, region=Mississippi Portal
Warning: No data found for column=primary_product_grain, year=2005, region=Southern Seaboard
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2005, region=Southern Seaboard
Warning: No data found for column=total_gross_value_of_production, year=2005, region=Southern Seaboard
Warning: No data found for column=seed, year=2005, region=Southern Seaboard
Warning: No data found for column=fertilizer_1, year=2005, region=Southern Seaboard
Warning: No data found for column=chemicals, year=2005, region=Southern Seaboard
Warning: No data found for column=custom_services, year=2005, region=Southern Seaboard
Warning: No data found for column=fuel_lube_and_electricity, year=2005, region=Southern Seaboard
Warning: No data found for column=repairs, year=2005, region=Southern Seaboard
Warning: No data found for column=other_variable_expenses_2, year=2005, region=Southern Seaboard
Warning: No data found for column=interest_on_operating_inputs, year=2005, region=Southern Seaboard
Warning: No data found for column=total_operating_costs, year=2005, region=Southern Seaboard
Warning: No data found for column=hired_labor, year=2005, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_unpaid_labor, year=2005, region=Southern Seaboard
Warning: No data found for column=capital_recovery_of_machinery_and_equipment, year=2005, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_land, year=2005, region=Southern Seaboard
Warning: No data found for column=taxes_and_insurance, year=2005, region=Southern Seaboard
Warning: No data found for column=general_farm_overhead, year=2005, region=Southern Seaboard
Warning: No data found for column=total_allocated_overhead, year=2005, region=Southern Seaboard
Warning: No data found for column=total_costs_listed, year=2005, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_total_costs_listed, year=2005, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_operating_costs, year=2005, region=Southern Seaboard
Warning: No data found for column=primary_product_grain, year=2005, region=Mississippi Portal
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2005, region=Mississippi Portal
Warning: No data found for column=total_gross_value_of_production, year=2005, region=Mississippi Portal
Warning: No data found for column=seed, year=2005, region=Mississippi Portal
Warning: No data found for column=fertilizer_1, year=2005, region=Mississippi Portal
Warning: No data found for column=chemicals, year=2005, region=Mississippi Portal
Warning: No data found for column=custom_services, year=2005, region=Mississippi Portal
Warning: No data found for column=fuel_lube_and_electricity, year=2005, region=Mississippi Portal
Warning: No data found for column=repairs, year=2005, region=Mississippi Portal
Warning: No data found for column=other_variable_expenses_2, year=2005, region=Mississippi Portal
Warning: No data found for column=interest_on_operating_inputs, year=2005, region=Mississippi Portal
Warning: No data found for column=total_operating_costs, year=2005, region=Mississippi Portal
Warning: No data found for column=hired_labor, year=2005, region=Mississippi Portal
Warning: No data found for column=opportunity_cost_of_unpaid_labor, year=2005, region=Mississippi Portal
Warning: No data found for column=capital_recovery_of_machinery_and_equipment, year=2005, region=Mississippi Portal
Warning: No data found for column=opportunity_cost_of_land, year=2005, region=Mississippi Portal
Warning: No data found for column=taxes_and_insurance, year=2005, region=Mississippi Portal
Warning: No data found for column=general_farm_overhead, year=2005, region=Mississippi Portal
Warning: No data found for column=total_allocated_overhead, year=2005, region=Mississippi Portal
Warning: No data found for column=total_costs_listed, year=2005, region=Mississippi Portal
Warning: No data found for column=value_of_production_less_total_costs_listed, year=2005, region=Mississippi Portal
Warning: No data found for column=value_of_production_less_operating_costs, year=2005, region=Mississippi Portal
Warning: No data found for column=primary_product_grain, year=2006, region=Southern Seaboard
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2006, region=Southern Seaboard
Warning: No data found for column=total_gross_value_of_production, year=2006, region=Southern Seaboard
Warning: No data found for column=seed, year=2006, region=Southern Seaboard
Warning: No data found for column=fertilizer_1, year=2006, region=Southern Seaboard
Warning: No data found for column=chemicals, year=2006, region=Southern Seaboard
Warning: No data found for column=custom_services, year=2006, region=Southern Seaboard
Warning: No data found for column=fuel_lube_and_electricity, year=2006, region=Southern Seaboard
Warning: No data found for column=repairs, year=2006, region=Southern Seaboard
Warning: No data found for column=other_variable_expenses_2, year=2006, region=Southern Seaboard
Warning: No data found for column=interest_on_operating_inputs, year=2006, region=Southern Seaboard
Warning: No data found for column=total_operating_costs, year=2006, region=Southern Seaboard
Warning: No data found for column=hired_labor, year=2006, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_unpaid_labor, year=2006, region=Southern Seaboard
Warning: No data found for column=capital_recovery_of_machinery_and_equipment, year=2006, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_land, year=2006, region=Southern Seaboard
Warning: No data found for column=taxes_and_insurance, year=2006, region=Southern Seaboard
Warning: No data found for column=general_farm_overhead, year=2006, region=Southern Seaboard
Warning: No data found for column=total_allocated_overhead, year=2006, region=Southern Seaboard
Warning: No data found for column=total_costs_listed, year=2006, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_total_costs_listed, year=2006, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_operating_costs, year=2006, region=Southern Seaboard
Warning: No data found for column=primary_product_grain, year=2006, region=Mississippi Portal
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2006, region=Mississippi Portal
Warning: No data found for column=total_gross_value_of_production, year=2006, region=Mississippi Portal
Warning: No data found for column=seed, year=2006, region=Mississippi Portal
Warning: No data found for column=fertilizer_1, year=2006, region=Mississippi Portal
Warning: No data found for column=chemicals, year=2006, region=Mississippi Portal
Warning: No data found for column=custom_services, year=2006, region=Mississippi Portal
Warning: No data found for column=fuel_lube_and_electricity, year=2006, region=Mississippi Portal
Warning: No data found for column=repairs, year=2006, region=Mississippi Portal
Warning: No data found for column=other_variable_expenses_2, year=2006, region=Mississippi Portal
Warning: No data found for column=interest_on_operating_inputs, year=2006, region=Mississippi Portal
Warning: No data found for column=total_operating_costs, year=2006, region=Mississippi Portal
Warning: No data found for column=hired_labor, year=2006, region=Mississippi Portal
Warning: No data found for column=opportunity_cost_of_unpaid_labor, year=2006, region=Mississippi Portal
Warning: No data found for column=capital_recovery_of_machinery_and_equipment, year=2006, region=Mississippi Portal
Warning: No data found for column=opportunity_cost_of_land, year=2006, region=Mississippi Portal
Warning: No data found for column=taxes_and_insurance, year=2006, region=Mississippi Portal
Warning: No data found for column=general_farm_overhead, year=2006, region=Mississippi Portal
Warning: No data found for column=total_allocated_overhead, year=2006, region=Mississippi Portal
Warning: No data found for column=total_costs_listed, year=2006, region=Mississippi Portal
Warning: No data found for column=value_of_production_less_total_costs_listed, year=2006, region=Mississippi Portal
Warning: No data found for column=value_of_production_less_operating_costs, year=2006, region=Mississippi Portal
Warning: No data found for column=primary_product_grain, year=2007, region=Southern Seaboard
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2007, region=Southern Seaboard
Warning: No data found for column=total_gross_value_of_production, year=2007, region=Southern Seaboard
Warning: No data found for column=seed, year=2007, region=Southern Seaboard
Warning: No data found for column=fertilizer_1, year=2007, region=Southern Seaboard
Warning: No data found for column=chemicals, year=2007, region=Southern Seaboard
Warning: No data found for column=custom_services, year=2007, region=Southern Seaboard
Warning: No data found for column=fuel_lube_and_electricity, year=2007, region=Southern Seaboard
Warning: No data found for column=repairs, year=2007, region=Southern Seaboard
Warning: No data found for column=other_variable_expenses_2, year=2007, region=Southern Seaboard
Warning: No data found for column=interest_on_operating_inputs, year=2007, region=Southern Seaboard
Warning: No data found for column=total_operating_costs, year=2007, region=Southern Seaboard
Warning: No data found for column=hired_labor, year=2007, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_unpaid_labor, year=2007, region=Southern Seaboard
Warning: No data found for column=capital_recovery_of_machinery_and_equipment, year=2007, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_land, year=2007, region=Southern Seaboard
Warning: No data found for column=taxes_and_insurance, year=2007, region=Southern Seaboard
Warning: No data found for column=general_farm_overhead, year=2007, region=Southern Seaboard
Warning: No data found for column=total_allocated_overhead, year=2007, region=Southern Seaboard
Warning: No data found for column=total_costs_listed, year=2007, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_total_costs_listed, year=2007, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_operating_costs, year=2007, region=Southern Seaboard
Warning: No data found for column=primary_product_grain, year=2007, region=Mississippi Portal
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2007, region=Mississippi Portal
Warning: No data found for column=total_gross_value_of_production, year=2007, region=Mississippi Portal
Warning: No data found for column=seed, year=2007, region=Mississippi Portal
Warning: No data found for column=fertilizer_1, year=2007, region=Mississippi Portal
Warning: No data found for column=chemicals, year=2007, region=Mississippi Portal
Warning: No data found for column=custom_services, year=2007, region=Mississippi Portal
Warning: No data found for column=fuel_lube_and_electricity, year=2007, region=Mississippi Portal
Warning: No data found for column=repairs, year=2007, region=Mississippi Portal
Warning: No data found for column=other_variable_expenses_2, year=2007, region=Mississippi Portal
Warning: No data found for column=interest_on_operating_inputs, year=2007, region=Mississippi Portal
Warning: No data found for column=total_operating_costs, year=2007, region=Mississippi Portal
Warning: No data found for column=hired_labor, year=2007, region=Mississippi Portal
Warning: No data found for column=opportunity_cost_of_unpaid_labor, year=2007, region=Mississippi Portal
Warning: No data found for column=capital_recovery_of_machinery_and_equipment, year=2007, region=Mississippi Portal
Warning: No data found for column=opportunity_cost_of_land, year=2007, region=Mississippi Portal
Warning: No data found for column=taxes_and_insurance, year=2007, region=Mississippi Portal
Warning: No data found for column=general_farm_overhead, year=2007, region=Mississippi Portal
Warning: No data found for column=total_allocated_overhead, year=2007, region=Mississippi Portal
Warning: No data found for column=total_costs_listed, year=2007, region=Mississippi Portal
Warning: No data found for column=value_of_production_less_total_costs_listed, year=2007, region=Mississippi Portal
Warning: No data found for column=value_of_production_less_operating_costs, year=2007, region=Mississippi Portal
Warning: No data found for column=primary_product_grain, year=2008, region=Southern Seaboard
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2008, region=Southern Seaboard
Warning: No data found for column=total_gross_value_of_production, year=2008, region=Southern Seaboard
Warning: No data found for column=seed, year=2008, region=Southern Seaboard
Warning: No data found for column=fertilizer_1, year=2008, region=Southern Seaboard
Warning: No data found for column=chemicals, year=2008, region=Southern Seaboard
Warning: No data found for column=custom_services, year=2008, region=Southern Seaboard
Warning: No data found for column=fuel_lube_and_electricity, year=2008, region=Southern Seaboard
Warning: No data found for column=repairs, year=2008, region=Southern Seaboard
Warning: No data found for column=other_variable_expenses_2, year=2008, region=Southern Seaboard
Warning: No data found for column=interest_on_operating_inputs, year=2008, region=Southern Seaboard
Warning: No data found for column=total_operating_costs, year=2008, region=Southern Seaboard
Warning: No data found for column=hired_labor, year=2008, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_unpaid_labor, year=2008, region=Southern Seaboard
Warning: No data found for column=capital_recovery_of_machinery_and_equipment, year=2008, region=Southern Seaboard
Warning: No data found for column=opportunity_cost_of_land, year=2008, region=Southern Seaboard
Warning: No data found for column=taxes_and_insurance, year=2008, region=Southern Seaboard
Warning: No data found for column=general_farm_overhead, year=2008, region=Southern Seaboard
Warning: No data found for column=total_allocated_overhead, year=2008, region=Southern Seaboard
Warning: No data found for column=total_costs_listed, year=2008, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_total_costs_listed, year=2008, region=Southern Seaboard
Warning: No data found for column=value_of_production_less_operating_costs, year=2008, region=Southern Seaboard
Warning: No data found for column=primary_product_grain, year=2008, region=Mississippi Portal
Warning: No data found for column=secondary_product_silage_straw_grazing, year=2008, region=Mississippi Portal
Warning: No data found for column=total_gross_value_of_production, year=2008, region=Mississippi Portal
Warning: No data found for column=seed, year=2008, region=Mississippi Portal
Warning: No data found for column=fertilizer_1, year=2008, region=Mississippi Portal
Warning: No data found for column=chemicals, year=2008, region=Mississippi Portal
Warning: No data found for column=custom_services, year=2008, region=Mississippi Portal
Warning: No data found for column=fuel_lube_and_electricity, year=2008, region=Mississippi Portal
Warning: No data found for column=repairs, year=2008, region=Mississippi Portal
Warning: No data found for column=other_variable_expenses_2, year=2008, region=Mississippi Portal
Warning: No data found for column=interest_on_operating_inputs, year=2008, region=Mississippi Portal

In [48]:
# Get actual years present in data and all possible years
actual_years = set(df_a['year'].unique())
all_regions = df_a['region'].unique()

# Decide on year range you want to include
min_year = min(actual_years)
max_year = max(actual_years)
all_years = range(min_year, max_year + 1)

num = 0
for year in all_years:
    for region in all_regions:
        cop_1.loc[num, 'year'] = year
        cop_1.loc[num, 'region'] = region
        
        # Check if this year exists in data
        if year in actual_years:
            # Year exists - try to get data
            for col in cop_1.columns:
                if col not in ['year', 'region']:
                    filtered = df_a[(df_a['column'] == col) & 
                                    (df_a['year'] == year) & 
                                    (df_a['region'] == region)]
                    
                    if not filtered.empty:
                        cop_1.loc[num, col] = filtered['value'].iloc[0]
                    else:
                        cop_1.loc[num, col] = np.nan
        else:
            # Year doesn't exist in data - fill all with NaN
            for col in cop_1.columns:
                if col not in ['year', 'region']:
                    cop_1.loc[num, col] = np.nan
        
        num += 1

In [49]:
cop_1

,primary_product_grain,secondary_product_silage_straw_grazing,total_gross_value_of_production,seed,fertilizer_1,chemicals,custom_services,fuel_lube_and_electricity,repairs,other_variable_expenses_2,...,capital_recovery_of_machinery_and_equipment,opportunity_cost_of_land,taxes_and_insurance,general_farm_overhead,total_allocated_overhead,total_costs_listed,value_of_production_less_total_costs_listed,value_of_production_less_operating_costs,region,year
0,110.95,3.32,114.27,7.61,18.61,7.36,6.77,6.14,9.0,0.58,...,43.0,37.52,3.7,6.59,107.78,165.19,-50.92,56.86,U.S. total,1998.0
1,125.97,13.58,139.55,13.25,37.91,3.76,6.46,4.36,7.19,0.5,...,38.6,63.4,3.26,7.21,130.28,205.47,-65.92,64.36,Heartland,1998.0
2,138.17,54.11,192.28,13.32,33.69,3.05,10.92,3.82,5.93,1.99,...,36.19,65.7,4.02,7.89,129.83,204.29,-12.01,117.82,Northern Crescent,1998.0
3,100.1,1.74,101.84,7.64,14.78,10.61,4.04,4.25,8.1,0.16,...,41.23,35.09,3.76,6.32,98.62,149.39,-47.55,51.07,Northern Great Plains,1998.0
4,103.74,2.24,105.98,5.13,14.27,3.3,8.07,7.03,8.84,0.15,...,40.66,28.18,3.03,5.67,95.11,143.02,-37.04,58.07,Prairie Gateway,1998.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,247.1,4.9,252.0,13.31,50.69,9.53,17.9,13.46,29.93,0.4,...,117.7,43.55,6.26,11.8,199.1,337.57,-85.57,113.53,Prairie Gateway,2024.0
239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Southern Seaboard,2024.0
240,349.66,10.33,359.99,22.03,65.4,32.95,17.16,15.95,34.23,0.8,...,135.15,72.51,13.72,15.52,264.7,457.75,-97.76,166.94,Basin and Range,2024.0
241,307.78,10.77,318.55,25.18,49.99,21.34,10.7,22.71,39.59,5.92,...,156.63,97.73,11.38,16.88,309.5,489.15,-170.6,138.9,Fruitful Rim,2024.0
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mississippi Portal,2024.0

    Transform a long-format dataframe to wide format with year and region as rows.
    
    Parameters:
    -----------
    df_long : DataFrame
        Input dataframe in long format with columns: year, region, column, value
    year_col : str, default='year'
        Name of the year column
    region_col : str, default='region'
        Name of the region column
    column_col : str, default='column'
        Name of the column containing variable names
    value_col : str, default='value'
        Name of the column containing values
    fill_missing_years : bool, default=True
        If True, fills missing years with NaN or fill_value
        If False, only includes years that exist in the data
    fill_value : any, default=np.nan
        Value to use for missing data
    
    Returns:
    --------
    DataFrame in wide format with columns: year, region, and all variable columns

In [86]:
df_a[(df_a["column"] == "primary_product_grain") & 
                                      (df_a["year"] == 2000) & 
                                      (df_a["region"] == "U.S. total")]["value"].iloc[0]

np.float64(92.5)

In [87]:
a_a = {"year": 2000, "region": "U.S. total"}
a_a["primary_product_grain"] = 92.5
a_a

{'year': 2000, 'region': 'U.S. total', 'primary_product_grain': 92.5}

# function transform data

In [50]:
def transform_long_to_wide(df_long, year_col='year', region_col='region', 
                          column_col='column', value_col='value', 
                          fill_missing_years=True, fill_value=np.nan):
    
    # Get unique values
    actual_years = set(df_long[year_col].unique())
    all_regions = df_long[region_col].unique()
    all_columns = df_long[column_col].unique()
    
    # Determine year range
    min_year = min(actual_years)
    max_year = max(actual_years)
    
    if fill_missing_years:
        all_years = range(min_year, max_year + 1)
    else:
        all_years = sorted(actual_years)
    
    # Create an empty dataframe for results
    result_data = []
    
    for year in all_years:
        for region in all_regions:
            # Create a row dictionary
            row = {year_col: year, region_col: region}
            
            # Check if this year exists in data
            if year in actual_years:
                # Year exists - try to get data for each column
                for col in all_columns:
                    filtered = df_long[(df_long[column_col] == col) & 
                                      (df_long[year_col] == year) & 
                                      (df_long[region_col] == region)]
                    
                    if not filtered.empty:
                        row[col] = filtered[value_col].iloc[0]
                    else:
                        row[col] = fill_value
            else:
                # Year doesn't exist in data - fill all with fill_value
                for col in all_columns:
                    row[col] = fill_value
            
            result_data.append(row)
    
    # Convert to DataFrame
    result_df = pd.DataFrame(result_data)
    
    # Reorder columns: year, region, then alphabetically sorted other columns
    other_cols = sorted([col for col in result_df.columns if col not in [year_col, region_col]])
    result_df = result_df[[year_col, region_col] + other_cols]
    
    return result_df

In [51]:
df_a = df_1.loc[df_1['units']=='dollars per planted acre']
df_a

,commodity,category,item,item2,units,size,region,country,year,value,survey_base_year,note,column
0,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,1998,110.95,Base survey of 1998,NaN,primary_product_grain
1,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,1999,95.73,Base survey of 1998,NaN,primary_product_grain
2,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2000,92.50,Base survey of 1998,NaN,primary_product_grain
3,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2001,95.22,Base survey of 1998,NaN,primary_product_grain
4,Wheat,Gross value of production,"Primary product, grain","Primary product, grain",dollars per planted acre,No specific size,U.S. total,United States,2002,91.51,Base survey of 1998,NaN,primary_product_grain
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4417,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,1999,60.03,Base survey of 1998,NaN,value_of_production_less_operating_costs
4418,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,2000,73.56,Base survey of 1998,NaN,value_of_production_less_operating_costs
4419,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,2001,58.00,Base survey of 1998,NaN,value_of_production_less_operating_costs
4420,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,2002,51.06,Base survey of 1998,NaN,value_of_production_less_operating_costs
4421,Wheat,Net value,Value of production less operating costs,Value of production less operating costs,dollars per planted acre,No specific size,Mississippi Portal,United States,2003,55.41,Base survey of 1998,NaN,value_of_production_less_operating_costs

In [57]:
df_a_1 = transform_long_to_wide(df_a, year_col='year', region_col='region', 
                          column_col='column', value_col='value', 
                          fill_missing_years=True, fill_value=np.nan)
file_path = ".\data_warehouse\wheat_dollars_per_planted_acre.gzip"
df_a_1.to_parquet(file_path)
print(f"\nDataFrame successfully saved to {file_path}")

DataFrame successfully saved to .\data_warehouse\wheat_dollars_per_planted_acre.gzip

In [75]:
print(df_a.column.nunique())
print(df_a_1.shape)

22
(243, 24)

In [76]:
print(df_a.column.unique())
print(df_a_1.columns)

['primary_product_grain' 'secondary_product_silage_straw_grazing'
 'total_gross_value_of_production' 'seed' 'fertilizer_1' 'chemicals'
 'custom_services' 'fuel_lube_and_electricity' 'repairs'
 'other_variable_expenses_2' 'interest_on_operating_inputs'
 'total_operating_costs' 'hired_labor' 'opportunity_cost_of_unpaid_labor'
 'capital_recovery_of_machinery_and_equipment' 'opportunity_cost_of_land'
 'taxes_and_insurance' 'general_farm_overhead' 'total_allocated_overhead'
 'total_costs_listed' 'value_of_production_less_total_costs_listed'
 'value_of_production_less_operating_costs']
Index(['year', 'region', 'capital_recovery_of_machinery_and_equipment',
       'chemicals', 'custom_services', 'fertilizer_1',
       'fuel_lube_and_electricity', 'general_farm_overhead', 'hired_labor',
       'interest_on_operating_inputs', 'opportunity_cost_of_land',
       'opportunity_cost_of_unpaid_labor', 'other_variable_expenses_2',
       'primary_product_grain', 'repairs',
       'secondary_product_silage_straw_grazing', 'seed', 'taxes_and_insurance',
       'total_allocated_overhead', 'total_costs_listed',
       'total_gross_value_of_production', 'total_operating_costs',
       'value_of_production_less_operating_costs',
       'value_of_production_less_total_costs_listed'],
      dtype='object')

In [59]:
df_b = df_1.loc[df_1['units']=='bushels per planted acre']

In [61]:
df_b_1 = transform_long_to_wide(df_b, year_col='year', region_col='region', 
                          column_col='column', value_col='value', 
                          fill_missing_years=True, fill_value=np.nan)
file_path = ".\data_warehouse\wheat_bushels_per_planted_acre.gzip"
df_b_1.to_parquet(file_path)
print(f"\nDataFrame successfully saved to {file_path}")

DataFrame successfully saved to .\data_warehouse\wheat_bushels_per_planted_acre.gzip

In [62]:
df_c = df_1.loc[df_1['units']=='dollars per bushel at harvest']

In [63]:
df_c_1 = transform_long_to_wide(df_c, year_col='year', region_col='region', 
                          column_col='column', value_col='value', 
                          fill_missing_years=True, fill_value=np.nan)
file_path = ".\data_warehouse\wheat_dollars_per_bushel_at_harvest.gzip"
df_c_1.to_parquet(file_path)
print(f"\nDataFrame successfully saved to {file_path}")

DataFrame successfully saved to .\data_warehouse\wheat_dollars_per_bushel_at_harvest.gzip

In [67]:
df_d = df_1.loc[df_1['units']=='planted acres']
df_d

,commodity,category,item,item2,units,size,region,country,year,value,survey_base_year,note,column
4824,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,U.S. total,United States,1998,296.0,Base survey of 1998,NaN,enterprise_size
4825,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,U.S. total,United States,1999,296.0,Base survey of 1998,NaN,enterprise_size
4826,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,U.S. total,United States,2000,296.0,Base survey of 1998,NaN,enterprise_size
4827,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,U.S. total,United States,2001,296.0,Base survey of 1998,NaN,enterprise_size
4828,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,U.S. total,United States,2002,296.0,Base survey of 1998,NaN,enterprise_size
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5020,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,Mississippi Portal,United States,1999,232.0,Base survey of 1998,NaN,enterprise_size
5021,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,Mississippi Portal,United States,2000,232.0,Base survey of 1998,NaN,enterprise_size
5022,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,Mississippi Portal,United States,2001,232.0,Base survey of 1998,NaN,enterprise_size
5023,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,Mississippi Portal,United States,2002,232.0,Base survey of 1998,NaN,enterprise_size
5024,Wheat,Supporting information,Enterprise size,Enterprise size (planted acres),planted acres,No specific size,Mississippi Portal,United States,2003,232.0,Base survey of 1998,NaN,enterprise_size

In [79]:
df_d.column.unique()

array(['enterprise_size'], dtype=object)

In [81]:
df_d_1 = transform_long_to_wide(df_d, year_col='year', region_col='region', 
                          column_col='column', value_col='value', 
                          fill_missing_years=True, fill_value=np.nan)
file_path = ".\data_warehouse\wheat_planted_acres.gzip"
df_d_1.to_parquet(file_path)
print(f"\nDataFrame successfully saved to {file_path}")

DataFrame successfully saved to .\data_warehouse\wheat_planted_acres.gzip

In [82]:
df_e = df_1.loc[df_1['units']=='percent of acres']

In [83]:
df_e_1 = transform_long_to_wide(df_e, year_col='year', region_col='region', 
                          column_col='column', value_col='value', 
                          fill_missing_years=True, fill_value=np.nan)
file_path = ".\data_warehouse\wheat_percent_of_acres.gzip"
df_e_1.to_parquet(file_path)
print(f"\nDataFrame successfully saved to {file_path}")

DataFrame successfully saved to .\data_warehouse\wheat_percent_of_acres.gzip

In [89]:
file_path = ".\data_warehouse\wheat_total_data.gzip"
df_1.to_parquet(file_path)
print(f"\nDataFrame successfully saved to {file_path}")

DataFrame successfully saved to .\data_warehouse\wheat_total_data.gzip

In [24]:
df_e = pd.DataFrame(columns = ["category","column_name"])
df_e['column_name'] = df_1.column.unique()
df_e

   category                                  column_name
0       NaN                        primary_product_grain
1       NaN       secondary_product_silage_straw_grazing
2       NaN              total_gross_value_of_production
3       NaN                                         seed
4       NaN                                 fertilizer_1
5       NaN                                    chemicals
6       NaN                              custom_services
7       NaN                    fuel_lube_and_electricity
8       NaN                                      repairs
9       NaN                    other_variable_expenses_2
10      NaN                 interest_on_operating_inputs
11      NaN                        total_operating_costs
12      NaN                                  hired_labor
13      NaN             opportunity_cost_of_unpaid_labor
14      NaN  capital_recovery_of_machinery_and_equipment
15      NaN                     opportunity_cost_of_land
16      NaN                          taxes_and_insurance
17      NaN                        general_farm_overhead
18      NaN                     total_allocated_overhead
19      NaN                           total_costs_listed
20      NaN  value_of_production_less_total_costs_listed
21      NaN     value_of_production_less_operating_costs
22      NaN                                        yield
23      NaN                                        price
24      NaN                              enterprise_size
25      NaN                                 winter_wheat
26      NaN                               winter_wheat_3
27      NaN                                 spring_wheat
28      NaN                               spring_wheat_3
29      NaN                                  durum_wheat
30      NaN                                durum_wheat_3
31      NaN                                      dryland
32      NaN                                    dryland_3
33      NaN                                    irrigated
34      NaN                                  irrigated_3

In [26]:
for i in df_1.column.unique():
    df_e.loc[df_e['column_name']==i, ['category']] = df_1.loc[df_1['column']==i, ['category']]['category'].unique()[0]

In [27]:
df_e

                     category                                  column_name
0   Gross value of production                        primary_product_grain
1   Gross value of production       secondary_product_silage_straw_grazing
2   Gross value of production              total_gross_value_of_production
3             Operating costs                                         seed
4             Operating costs                                 fertilizer_1
5             Operating costs                                    chemicals
6             Operating costs                              custom_services
7             Operating costs                    fuel_lube_and_electricity
8             Operating costs                                      repairs
9             Operating costs                    other_variable_expenses_2
10            Operating costs                 interest_on_operating_inputs
11            Operating costs                        total_operating_costs
12         Allocated overhead                                  hired_labor
13         Allocated overhead             opportunity_cost_of_unpaid_labor
14         Allocated overhead  capital_recovery_of_machinery_and_equipment
15         Allocated overhead                     opportunity_cost_of_land
16         Allocated overhead                          taxes_and_insurance
17         Allocated overhead                        general_farm_overhead
18         Allocated overhead                     total_allocated_overhead
19               Costs listed                           total_costs_listed
20                  Net value  value_of_production_less_total_costs_listed
21                  Net value     value_of_production_less_operating_costs
22     Supporting information                                        yield
23     Supporting information                                        price
24     Supporting information                              enterprise_size
25       Production practices                                 winter_wheat
26       Production practices                               winter_wheat_3
27       Production practices                                 spring_wheat
28       Production practices                               spring_wheat_3
29       Production practices                                  durum_wheat
30       Production practices                                durum_wheat_3
31       Production practices                                      dryland
32       Production practices                                    dryland_3
33       Production practices                                    irrigated
34       Production practices                                  irrigated_3

In [28]:
file_path = ".\data_warehouse\wheat_column_name_category.gzip"
df_e.to_parquet(file_path)
print(f"\nDataFrame successfully saved to {file_path}")

DataFrame successfully saved to .\data_warehouse\wheat_column_name_category.gzip